### ISSUE TITLE
DB에 작업하는 부분 예외처리 추가 필요

### ISSUE THREAD

**Issue by whdgnszz1** [jane5am/spring_batch#1]
# 이슈사항
데이터베이스 접근 및 저장 과정에서 발생할 수 있는 예외를 처리하여 시스템의 안정성을 높입니다.

# 이슈 내용
package com.example.demo.batch.service 패키지에 있는 DailyTop5Videos 메서드의 경우 아래의 코드 부분은 try-catch 구문을 사용하여 예외처리가 필요해보입니다.

```java
dailyTop5VideosRepository.save(dailyVideoViewsTop5);
```

**Comment by jane5am** [comment]
logger.error("Error saving dailyVideoViewsTop5 for videoId: " + videoId, e); 추가하여 수정완료 했습니다. 감사합니다!
